"""
Trains the Q-SHIELD demo anomaly-detection pipeline:
  1. IsolationForest (unsupervised anomaly detector) over the 18 security features
  2. RandomForestClassifier (supervised) as a secondary classifier, evaluated
     with a held-out test split so accuracy numbers reported are real, not invented.

Run: python ml/train_model.py
Reads: data/sample_security_events.csv (generated by generate_dataset.py)
Writes: ml/models/isolation_forest.joblib, ml/models/random_forest.joblib,
        ml/models/scaler.joblib, ml/models/metrics.json
"""
import json
from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

from generate_dataset import FEATURES, generate

ROOT = Path(__file__).resolve().parents[2]
DATA_PATH = ROOT / "data" / "sample_security_events.csv"
MODELS_DIR = Path(__file__).resolve().parent / "models"


def load_or_generate() -> pd.DataFrame:
    if DATA_PATH.exists():
        return pd.read_csv(DATA_PATH)
    df = generate()
    DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(DATA_PATH, index=False)
    return df


def main():
    df = load_or_generate()
    X = df[FEATURES].values
    y = df["label"].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )

    scaler = StandardScaler().fit(X_train)
    X_train_s = scaler.transform(X_train)
    X_test_s = scaler.transform(X_test)

    # Unsupervised anomaly detector
    iso = IsolationForest(
        n_estimators=200, contamination=float(y_train.mean()), random_state=42
    )
    iso.fit(X_train_s)

    # Supervised classifier for evaluated accuracy metrics
    rf = RandomForestClassifier(n_estimators=300, max_depth=8, random_state=42)
    rf.fit(X_train_s, y_train)
    y_pred = rf.predict(X_test_s)
    y_proba = rf.predict_proba(X_test_s)[:, 1]

    metrics = {
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "accuracy": round(float(accuracy_score(y_test, y_pred)), 4),
        "precision": round(float(precision_score(y_test, y_pred, zero_division=0)), 4),
        "recall": round(float(recall_score(y_test, y_pred, zero_division=0)), 4),
        "f1": round(float(f1_score(y_test, y_pred, zero_division=0)), 4),
        "roc_auc": round(float(roc_auc_score(y_test, y_proba)), 4),
        "note": "Metrics computed on a held-out test split of SYNTHETIC demo data. Not a claim of real-world detection accuracy.",
    }

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(iso, MODELS_DIR / "isolation_forest.joblib")
    joblib.dump(rf, MODELS_DIR / "random_forest.joblib")
    joblib.dump(scaler, MODELS_DIR / "scaler.joblib")
    with open(MODELS_DIR / "metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)

    print(json.dumps(metrics, indent=2))
    print(f"Models saved to {MODELS_DIR}")


if __name__ == "__main__":
    main()
